spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

  codec:
    max-in-memory-size=100MB:
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/dockerdb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access=false:
    repositories:
      enabled=true:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
api:
  services:
    skyPicker:
      baseUrl: https://run.mocky.io
      headers: apikey=J7JHY6NB766G542APQLS32
      endpoints:
        filter:
          path: /v3/c66de63e-866e-4d63-a6eb-c0c649a59518
          method: GET
          timeout: 20
          v: 3
        locations:
          path: /v3/3796db51-102d-4ea3-8433-c8a78c348c19
          method: GET
          timeout: 20
springdoc:
  api-docs:
    path=/api-docs:
server:
  port : 8085
database:
  default: elasticsearch
elasticsearch:
  url: localhost:9200


