package org.pt.flightbooking.enums;

public enum Context {
    SUBMIT_FLIGHT_SEARCH_SUCCESS,
    QUANTITY_FLIGHTS_IN_SEARCH,
    HTTP_RESPONSE,
    HTTP_STATUS_CODE,
    EXCEPTION,
    FLIGHT_RECORD_CREATED,
    FLIGHT_RECORDS_COUNT,
    FLIGHT_RECORD_ID
}